librocksdb_sys/build.sh
zlib 1.2.10 no longer available.
@siddontang @BusyJay PTAL
=> upgrade zlib to 1.2.11

librocksdb_sys/build.sh
fix zlib include dir error.
@siddontang @BusyJay @disksing PTAL
=> upgrade zlib include dir

test/test.rs, test/test_prefix_extractor.rs
=> Add test for prefix extractor compatibility

README.md, librocksdb_sys/src/lib.rs, src/main.rs, src/rocksdb.rs, src/rocksdb_options.rs
`rocksdb_options_set_filter_deletes` is deleted in facebook/rocksdb#1407.
@siddontang @zhangjinpeng1987 PTAL
=> fix undefined symbols

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/external_file.rs, src/rocksdb.rs, src/rocksdb_options.rs, src/slice_transform.rs, test/test.rs, test/test_compact_range.rs, test/test_compaction_filter.rs, test/test_ingest_external_file.rs, test/test_iterator.rs, test/test_multithreaded.rs, test/test_prefix_extractor.rs, test/test_rocksdb_options.rs, test/test_slice_transform.rs, test/test_statistics.rs
Export RocksDB internal statistics.
@BusyJay @siddontang PTAL
=> export RocksDB statistics

src/lib.rs
export DBStatisticsTickerType && DBStatisticsHistogramType.
@siddontang @hhkbp2 PTAL
=> export statistics types

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, test/test_statistics.rs
Get histogram detail from rocksdb's statistics.
@siddontang @BusyJay PTAL
=> get histogram detail

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, test/test_rocksdb_options.rs
Support memtable_insert_with_hint_prefix_extractor to speedup insert.
@siddontang @disksing PTAL
=> support memtable_insert_with_hint_prefix_extractor

librocksdb_sys/build.sh
=> support rocksdb 5.1.2

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, test/test_statistics.rs
@siddontang @zhangjinpeng1987 @hhkbp2 PTAL
=> introduce savepoint

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
Hi,
This PR is for issue #19 
PTAL @zhangjinpeng1987 @siddontang @BusyJay
=> add delete range interface

src/rocksdb.rs, src/rocksdb_options.rs
Hi,
This PR tries to address comments listed after PR #25 is merged.
PTAL @BusyJay @siddontang @zhangjinpeng1987
=> mark new_with constructor unsafe for Options

Cargo.toml, librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs
=> add sse feature

Makefile, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/format-diff.sh, librocksdb_sys/crocksdb/rocksdb/c.h
=> add rocksdb format tool and format code

librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> support pin l0 filter and index in cache

librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> support log ttl and add test

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> max subcompactions

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
=> flush api for specified cf

librocksdb_sys/build.sh
ref facebook/rocksdb#2164
close #39
=> enable o2 optimization

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> support optimize_filters_for_hits

librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> support dynamic level bytes

librocksdb_sys/build.sh
=> upgrade rocksdb to 5.2.1

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
Add bytes_per_sync and wal_bytes_per_sync
=> Add bytes_per_sync and wal_bytes_per_sync options

librocksdb_sys/build.sh, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/test_rocksdb_options.rs
=> Add support for db.sync_wal()

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, src/rocksdb_options.rs
=> fix redefinition error

librocksdb_sys/src/lib.rs, tests/test_rocksdb_options.rs
=> fix redefinition err and warning

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> support direct io

librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> support compact range options

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
PTAL @zhangjinpeng1987 @siddontang
=> export writable_file_max_buffer_size option

librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
@siddontang @lishihai9017 PTAL
=> base compaction threads

librocksdb_sys/build.rs, librocksdb_sys/build.sh, librocksdb_sys/src/lib.rs
Add Xpress and ZSTD compression types.
@siddontang @ngaut PTAL
=> more compression types

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
=> writebatch with capacity

.gitignore, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_iterator.rs, tests/test_prefix_extractor.rs
using prefix_same_as_start in prefix seek simply our logic in some seeking scenario
=> export readopt of prefix_same_as_start

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> api: add set_delayed_write_rate method

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> rocksdb: add get_compression method

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> rocksdb: add get_compression_per_level method to Options

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
PTAL @andelf @zhangjinpeng1987 
I met some problems about ffi and fixed them, but I'm quite new to rust and don't know whether what I do is correct. 
=> rocksdb: add supported_compression function

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> rocksdb: add bottommost_compression method

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/event_listener.rs, src/lib.rs, src/rocksdb_options.rs, src/table_properties.rs, tests/test.rs, tests/test_event_listener.rs, tests/test_ingest_external_file.rs
Only some event callbacks are implemented, others can be implemented when necessary.
=> support event listener

src/rocksdb_options.rs, tests/test_ingest_external_file.rs
See https://github.com/pingcap/rust-rocksdb/issues/97
@zhangjinpeng1987 @BusyJay PTAL
=> ingestoption: make method signatures consistent

src/rocksdb.rs, tests/test.rs, tests/test_delete_range.rs, tests/test_event_listener.rs
=> Add some tests for delete_range

librocksdb_sys/src/lib.rs, src/main.rs, src/rocksdb_options.rs
=> Support max_compaction_bytes

README.md, circle.yml, librocksdb_sys/build.sh
This version rocksdb supports ingesting files into a database containing range deletions.
=> use rocksdb 5.6.1

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> support db_paths

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
PTAL @zhangjinpeng1987 @siddontang
=> support more read/write options

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/test_ingest_external_file.rs
PTAL @zhangjinpeng1987  @siddontang
=> support new DB operations

librocksdb_sys/src/lib.rs
PTAL @zhangjinpeng1987 @siddontang
=> add more statistics

tests/test_ingest_external_file.rs
@siddontang @zhangjinpeng1987 PTAL
=> tests: add more real world test case of ingest

tests/test.rs, tests/test_delete_files_in_range.rs
Test delete_files_in_range with snapshot and iterator.
=> add test for delete_files_in_range

librocksdb_sys/build.sh
1) support sse
2) Fix missing BYTES_PER_WRITE for pipeline write
=> use pingcap/5.7.3 rocksdb

tests/test_rocksdb_options.rs
Close https://github.com/pingcap/rust-rocksdb/issues/137
=> Fix `read_amp_bytes_per_bit` test

Cargo.toml, librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, rustfmt.toml, src/rocksdb.rs, src/rocksdb_options.rs, tests/test_delete_range.rs, tests/test_ingest_external_file.rs
- fix warnings
- update gcc
- use try shorthand
=> tiny cleanup

src/rocksdb.rs, tests/test_column_family.rs, tests/test_delete_range.rs, tests/test_ingest_external_file.rs, tests/test_read_only.rs
Keep consistent with `open_cf`.
=> use cf descriptor to create cf

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
Signed-off-by: UncP <uncp.xu@gmail.com>
=> add  `cache_index_and_filter_blocks_with_high_priority` option

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
=> Add fifo compaction options

src/rocksdb_options.rs, tests/test_rate_limiter.rs
Signed-off-by: UncP <uncp.xu@gmail.com>
impl Send for rate limiter to fix TiKV compilation error.
=> impl Send for rate limiter

librocksdb_sys/rocksdb/db/db_iter.cc, librocksdb_sys/rocksdb/db/db_iter_test.cc, librocksdb_sys/rocksdb/include/rocksdb/options.h, librocksdb_sys/rocksdb/options/options.cc
Pull upstream [change](https://github.com/pingcap/rocksdb/pull/6)
=> update rocksdb lower bound

Cargo.toml, tests/test.rs, tests/test_delete_files_in_range.rs
This test will not pass until https://github.com/facebook/rocksdb/pull/2843 is merged.
=> add delete files in range with delete range test

librocksdb_sys/rocksdb/CMakeLists.txt, librocksdb_sys/rocksdb/cmake/modules/FindNUMA.cmake, librocksdb_sys/rocksdb/cmake/modules/FindTBB.cmake
update this [commit](https://github.com/pingcap/rocksdb/pull/12).
=> rocksdb: cmake config checks

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
Add option to use the vector memtable, which may help in insert-only workload.
=> Add vector memtable option

src/rocksdb.rs
Input file names should be converted to C string.
=> Fix compact files

librocksdb_sys/rocksdb/db/external_sst_file_ingestion_job.cc
Cherry pick https://github.com/pingcap/rocksdb/commit/7a96f60b99a4b1d88afa9cb6c8d4052bd07c584e
=> Update rocksdb with a fix

librocksdb_sys/src/lib.rs
Some usages require these traits.
=> Add some common derived traits

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
enable us change block cache  capacity via tikv-ctl
=> set & get block cache capacity via cf_options

librocksdb_sys/rocksdb/db/compaction.cc
This is a cherry-pick from pingcap/rocksdb/release.
=> rocksdb: optimize sub compaction

librocksdb_sys/rocksdb/db/column_family.cc, librocksdb_sys/rocksdb/db/column_family.h, librocksdb_sys/rocksdb/db/compaction.cc, librocksdb_sys/rocksdb/db/compaction.h, librocksdb_sys/rocksdb/db/compaction_job.cc, librocksdb_sys/rocksdb/db/compaction_job_test.cc, librocksdb_sys/rocksdb/db/compaction_picker.cc, librocksdb_sys/rocksdb/db/compaction_picker.h, librocksdb_sys/rocksdb/db/compaction_picker_universal.cc, librocksdb_sys/rocksdb/db/db_impl.h, librocksdb_sys/rocksdb/db/db_impl_compaction_flush.cc, librocksdb_sys/rocksdb/db/db_impl_debug.cc, librocksdb_sys/rocksdb/db/db_range_del_test.cc, librocksdb_sys/rocksdb/include/rocksdb/options.h
Add max_subcompactions as a compaction option.
=> Update rocksdb from pingcap/rocksdb

librocksdb_sys/rocksdb/db/c.cc, librocksdb_sys/rocksdb/memtable/inlineskiplist.h
Paired with https://github.com/pingcap/rocksdb/pull/22.
Please only merge after merging https://github.com/pingcap/rocksdb/pull/22.
close #206
=> Fix C++ 8.1 build errors.

librocksdb_sys/rocksdb/db/compaction_picker.cc, librocksdb_sys/rocksdb/db/compaction_picker.h, librocksdb_sys/rocksdb/db/db_compaction_test.cc, librocksdb_sys/rocksdb/db/db_impl_compaction_flush.cc
https://github.com/pingcap/rocksdb/pull/23
=> librocksdb_sys: update rocksdb with CompactFiles related fixes

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/rocksdb/db/compaction_picker.cc, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb_options.rs, tests/test_compact_range.rs
Expose the bottommost level compaction option to make it more flexible.
=> *: add bottommost level compaction

src/merge_operator.rs
The `partial_merge_callback` always set `new_value_length` to 1 and will truncate the merged result:
[https://github.com/pingcap/rust-rocksdb/blob/348b5bc94d1b7aee486f04c7aacca7f1712cdae0/src/merge_operator.rs#L91](https://github.com/pingcap/rust-rocksdb/blob/348b5bc94d1b7aee486f04c7aacca7f1712cdae0/src/merge_operator.rs#L91)
Setting new_value_length to result length can fix this.
=> Fix incorrect merge result db reopened (#223)

librocksdb_sys/rocksdb/db/db_compaction_test.cc, librocksdb_sys/rocksdb/db/db_flush_test.cc, librocksdb_sys/rocksdb/db/db_impl.h, librocksdb_sys/rocksdb/db/db_impl_compaction_flush.cc, librocksdb_sys/rocksdb/db/db_impl_debug.cc, librocksdb_sys/rocksdb/db/db_test.cc, librocksdb_sys/rocksdb/db/listener_test.cc, librocksdb_sys/rocksdb/include/rocksdb/options.h, librocksdb_sys/rocksdb/utilities/transactions/transaction_test.cc
Ref: https://github.com/pingcap/rocksdb/pull/57
=> rocksdb: update subtree

src/metadata.rs, src/rocksdb.rs, tests/test_compact_range.rs, tests/test_compaction_filter.rs, tests/test_delete_range.rs, tests/test_iterator.rs, tests/test_prefix_extractor.rs, tests/test_rocksdb_options.rs
(cherry picked from commit e2e4ac2)
=> metadata: fix lifetime (#222)

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/src/lib.rs, src/event_listener.rs, src/lib.rs, tests/test_event_listener.rs
Export compaction reason for CompactionJobInfo.
=> Export compaction reason

src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
=> set_env for DBOptions

tests/cases/test_delete_files_in_range.rs
Previous implementation relies on auto compactions to move files to
the specific level, which is not reliable. This PR controls the
compaction manually to make sure the files will be placed at the
expected level.
Close #249
=> tests: fix test_delete_files_in_range

src/rocksdb.rs, src/rocksdb_options.rs
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
=> get env from DB

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/src/lib.rs, src/event_listener.rs, src/table_properties.rs, tests/cases/test_event_listener.rs
1, Expose the status of CompactionJobInfo
2, Check if the ptr of table_properties is not null
=> Fix event listener bug

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/src/lib.rs, src/event_listener.rs, src/table_properties.rs, tests/cases/test_event_listener.rs
(cherry picked from commit dc16c9b1109186a1baaf8e9babbbe7fbefdc404c)
=> Fix event listener bug (#267)

librocksdb_sys/crocksdb/c.cc
(cherry picked from commit 2088c8d4faa1f433f43e0de8d2558509a4027c2c)
=> fix shared_ptr misuse (#271)

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/titan.rs, tests/cases/test_titan.rs
expose a blob index encoder api for test
=> Add blob index encoder

.gitmodules, librocksdb_sys/build.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/libtitan_sys/Cargo.toml, librocksdb_sys/libtitan_sys/build.rs, librocksdb_sys/libtitan_sys/src/lib.rs
Adding pingcap/titan as submodule and adding related build scripts.
Tested with `cargo test`
=> Move Titan to separate repository

src/rocksdb.rs
=> [cherry-pick 2.1] Add status API (#285)

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, src/titan.rs, tests/cases/test_titan.rs
- Add `TitanReadOptions` 
- Update Titan `NewIterator` API to support `TitanReadOptions`
=> Add titan read option

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, src/titan.rs, tests/cases/test_titan.rs
cherry-pick of https://github.com/pingcap/rust-rocksdb/pull/309 and https://github.com/pingcap/rust-rocksdb/pull/306
=> cherry-pick some commits

librocksdb_sys/Cargo.toml, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/libtitan_sys/Cargo.toml, librocksdb_sys/libtitan_sys/build.rs, librocksdb_sys/src/lib.rs, src/rocksdb.rs
Cherry-picking changes:
c503e73 2019-07-02 yiwu@pingcap.com     Fix Titan portable build (#312)
c17648a 2019-07-01 yiwu@pingcap.com     Fix create_cf not passinig titan specific options to titan (#311)
=> Cherry-pick Titan related fixes

.gitmodules
rocksdb use skiplist with previous linked skiplist.
=> use prev seek skiplist

librocksdb_sys/Cargo.toml
=> Fix libtitan_sys sse flag

librocksdb_sys/build.rs
On some platforms jemalloc-sys adds a prefix when building its jemalloc. Thus it is not suitable to use jemalloc-sys to provide a jemalloc in such platforms, otherwise this will lead to a link error.
=> Ignore jemalloc option on specific platform

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_titan.rs
=> Add delete files in ranges API for titan (#317)

librocksdb_sys/src/lib.rs
fix ffi_try macro_rules so it can process empty-parameter functions
=> Fix ffi_try

librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
- fix a missed parameter in previous pr
- fix jemalloc-sys dependency, otherwise it can not link to executable correctly while jemalloc feature is enalbled.
=> Fix jemalloc allocator

src/compaction_filter.rs, src/event_listener.rs, src/main.rs, src/rocksdb_options.rs, src/slice_transform.rs, src/table_filter.rs, src/table_properties_collector.rs, src/table_properties_collector_factory.rs, tests/cases/test_rocksdb_options.rs, tests/cases/test_table_properties.rs, tests/cases/test_titan.rs
=> fix clippy warnings

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_column_family.rs
Signed-off-by: Little-Wallace liuwei@pingcap.com
Cherry-Pick [pingcap#338](https://github.com/pingcap/rust-rocksdb/pull/338) to master
=> Cherry-Pick Doubly-SkipList

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/titan.rs
Cherry-pick recent Titan changes included in https://github.com/pingcap/titan/pull/89
=> Cherry-pick Titan changes to tikv-3.0

.travis.yml, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs
Add interface to get count of each write stall reason.
=> add io stall stats interface

Cargo.toml, Makefile, librocksdb_sys/Cargo.toml, librocksdb_sys/libtitan_sys/Cargo.toml, librocksdb_sys/libtitan_sys/build.rs
Add feature to support updating titan to latest master before build.
=> add update titan script

Cargo.toml, librocksdb_sys/Cargo.toml, librocksdb_sys/libtitan_sys/Cargo.toml, librocksdb_sys/libtitan_sys/build.rs
=> build: remove update_titan feature

src/rocksdb.rs
Signed-off-by: Brian Anderson <andersrb@gmail.com>
This is for upcoming movement of more SST code into the tikv engine traits: http://github.com/brson/tikv/tree/engine-traits-sst
It's not feasible to do the abstraction with lifetimes, so this is a version using reference counting.
=> Add Rc-based SstFileReader iterators

Makefile
cherry-pick of #359 and #366 
And update rocksdb and titan by pass
=> add update rocksdb/titan script

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_titan.rs
=> Fix titan cf options for create_cf (#387)

.gitmodules, README.md
Signed-off-by: fredchenbj <cfworking@163.com>
=> submodules: fix url

src/lib.rs, src/perf_context.rs, src/rocksdb.rs, tests/cases/test_delete_files_in_range.rs, tests/cases/test_delete_range.rs, tests/cases/test_ingest_external_file.rs, tests/cases/test_iterator.rs, tests/cases/test_prefix_extractor.rs, tests/cases/test_rocksdb_options.rs, tests/cases/test_slice_transform.rs, tests/cases/test_table_properties.rs, tests/cases/test_titan.rs
=> iterator: fix error handling about valid (#411)

src/rocksdb.rs
=> remove a lint for old compilers

src/rocksdb.rs
Needed by https://github.com/tikv/tikv/pull/6209
=> Mark SequentialFile as Send

.gitmodules, README.md
Update Titan with changes:
```
b623e6b 2020-02-04 yiwu@pingcap.com     Sync titan directory when adding blob files (#136) (#141)
0ce4d66 2020-02-01 yiwu@pingcap.com     Fix GC stat not being updated after DeleteFilesInRange (#135) (#137)
```
Also fix submodule url.
=> [tikv-3.x] Update to latest Titan and fix submodule url

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
=> add multi batch write interface

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/perf_context.rs
=> add write thread wait time for perf context

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, src/titan.rs
Enable merge operator for titan.
=> add merge operator config

Makefile
Signed-off-by: Connor1996 <zbk602423539@gmail.com>
=> fix update rocksdb script

Cargo.toml, README.md, librocksdb_sys/Cargo.toml, librocksdb_sys/libtitan_sys/Cargo.toml, src/compaction_filter.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
=> Update to the latest dependencies

librocksdb_sys/crocksdb/c.cc, src/rocksdb.rs
renew branch of multibatch-write. Optimize for large write batch block other thread.
=> new multibatch write

librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs
Closes https://github.com/tikv/rust-rocksdb/issues/461
=> Making static linking of libstdc++ a feature

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs
Signed-off-by: Connor <zbk602423539@gmail.com>
=> Add API to run sst dump tool

src/rocksdb.rs, src/rocksdb_options.rs, tests/cases/test_titan.rs
Signed-off-by: Connor1996 <zbk602423539@gmail.com>
=> Fix set rocksdb options after setting titan options 

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/compaction_filter.rs
=> compaction filter: add bottommost level

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, scripts/format-diff.sh, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
=> support changing rate limiter dynamically (#510) (#516)

src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
=> add refill_period for creating rate limiter

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/perf_context.rs
Adding more perf context counters.
=> add more perf context counters

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
Signed-off-by: Connor1996 <zbk602423539@gmail.com>
=> Add compact on deletion support

librocksdb_sys/Cargo.toml
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
=> Remove useless features of bindgen

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_titan.rs
To fix https://github.com/tikv/tikv/issues/8661, we separate the DeleteBlobFiles from DeleteFiles API.
=> Add DeleteBlobFiles API for titan

.gitmodules, librocksdb_sys/bindings/aarch64-unknown-linux-gnu-bindings.rs, librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
Add initializer for new `WriteAmpBasedRateLimiter`, also update rocksdb to include this plugin brought by tikv/rocksdb#193.
=> Add support for WriteAmpBasedRateLimiter

librocksdb_sys/bindings/aarch64-unknown-linux-gnu-bindings.rs, librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
=> Add option for max-background-flushes and max-background-compactions (#550)

librocksdb_sys/bindings/aarch64-unknown-linux-gnu-bindings.rs, librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
Signed-off-by: Xintao <hunterlxt@live.com>
=> Add api to set compression option for bottommost level

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/src/lib.rs, src/compaction_filter.rs, src/lib.rs
Add `filter_v2` into trait `CompactionFilter`. And remove some useless ffi functions.
=> port filter_v2 for compaction filter

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
Port rate limiter's auto-tuned mode setter/getter, test case covers turning off auto-tuned for write-amp-based limiter.
=> dynamically modify auto-tuned mode of rate limiter

src/lib.rs
=> Import some variable public

librocksdb_sys/crocksdb/c.cc
=> Fix memory corruption caused by uninitialized fields

src/sst_partitioner.rs
Allow sst partitioner methods to be mutable. On RocksDB side these methods are not const methods, thus should be mutable.
=> change sst_partitioner calls to be mutable (#598)

.travis.yml
=> fix arm64 ci

src/rocksdb_options.rs
=> fix mut quantifier in option getters

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/event_listener.rs
=> Add base_input_level getter for CompactionJobInfo

src/rocksdb_options.rs
making get_write_global_seqno immutable method.
Signed-off-by: v01dstar <yang.zhang@pingcap.com>
=> Readability improvement

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/event_listener.rs, tests/cases/test_event_listener.rs
Add picked level of ingestion info and num_input_files_at_output_level of compaction info
=> Add picked level and num_input_files_at_output_level

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/encryption.rs
update rocksdb to include tikv/rocksdb#246 for tikv-4.x
include 6eb4fda4c486f519c5176789fc23b88e9a173dbe
=> rocksdb: Pick Atomize Rename operation related PRs into tikv-4.x

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/compaction_filter.rs, src/merge_operator.rs, src/table_filter.rs
It appears on MacOS with Clang, `bool` is not supported in C, causing compile error. Changing it to `char`.
=> fix mac build

src/write_batch.rs
Fix https://github.com/tikv/rust-rocksdb/issues/654
=> Fix WriteBatch::iterate memory leak

src/rocksdb.rs
=> fix ingest L0 bug

librocksdb_sys/src/lib.rs, src/event_listener.rs, src/logger.rs, src/rocksdb.rs, src/rocksdb_options.rs, src/table_filter.rs, src/table_properties_collector.rs, src/table_properties_collector_factory.rs, tests/cases/test_table_properties.rs, tests/cases/test_titan.rs
Signed-off-by: yuqi1129 <yuqi4733@gmail.com>
This PR tries to resolve issue https://github.com/tikv/rust-rocksdb/issues/513
Close #513.
=> Reduce boxing in callback structs

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_event_listener.rs
Signed-off-by: Xintao <hunterlxt@live.com>
=> Add delete_file interface

src/compaction_filter.rs, src/rocksdb_options.rs, src/slice_transform.rs, tests/cases/test_compaction_filter.rs, tests/cases/test_delete_range.rs, tests/cases/test_iterator.rs, tests/cases/test_prefix_extractor.rs, tests/cases/test_rocksdb_options.rs, tests/cases/test_slice_transform.rs
close https://github.com/tikv/rust-rocksdb/issues/513
Signed-off-by: Jayice <1185430411@qq.com>
=> Reduce boxing in callback

librocksdb_sys/src/lib.rs, src/rocksdb.rs
=> port env background threads setters

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/generate.py, librocksdb_sys/src/generated.rs, librocksdb_sys/src/lib.rs, src/lib.rs, src/perf_context.rs
Add some useful wrappers for https://github.com/tikv/rocksdb/pull/272.
Wait until https://github.com/tikv/rocksdb/pull/272 is merged, so the submodule can be updated to use the tikv fork.
=> Implement setting perf flags

README.md
=> Update `WriteBatch` example

librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/titan.rs
=> update Titan and remove deprecated APIs

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
Signed-off-by: Wenbo Zhang <ethercflow@gmail.com>
=> Optimize Commit pipeline performance

librocksdb_sys/crocksdb/c.cc
Signed-off-by: Wenbo Zhang <ethercflow@gmail.com>
=> Add missing symbol define

.gitmodules, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/titan.rs
=> *: update submodules

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
Ref https://github.com/tikv/rocksdb/pull/307
=> Expose seqno for multi-batch-write

Cargo.toml, librocksdb_sys/Cargo.toml
=> use patch to workaround cmake-rs bug

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/checkpoint.rs, src/compaction_filter.rs, src/lib.rs, src/rocksdb.rs, tests/cases/mod.rs, tests/cases/test_checkpoint.rs
supports checkpoint interface. http://rocksdb.org/blog/2015/11/10/use-checkpoints-for-efficient-snapshots.html
Signed-off-by: nolouch <nolouch@gmail.com>
=> supports checkpoint

.gitmodules
=> *: update rocksdb

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/main.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs, tests/cases/test_statistics.rs, tests/cases/test_titan.rs
=> support sharing statistics

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/compaction_filter.rs, src/comparator.rs, src/event_listener.rs, src/file_system.rs, src/logger.rs, src/main.rs, src/merge_operator.rs, src/metadata.rs, src/rocksdb.rs, src/rocksdb_options.rs, src/slice_transform.rs, src/sst_partitioner.rs, src/table_filter.rs, src/table_properties_collector.rs, src/table_properties_collector_factory.rs, src/write_batch.rs, tests/cases/test_rocksdb_options.rs, tests/cases/test_statistics.rs, tests/cases/test_titan.rs
=> refactor db statistics

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
=> port periodic work changes

librocksdb_sys/build.rs
Fixes https://github.com/rust-cross/cargo-zigbuild/issues/88
See also https://kazlauskas.me/entries/writing-proper-buildrs-scripts
cc @jiacai2050
=> Add cross compilation support to `librocksdb_sys`

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/compaction_filter.rs, src/lib.rs, src/perf_context.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/cases/test_compact_range.rs, tests/cases/test_delete_files_in_range.rs, tests/cases/test_delete_range.rs, tests/cases/test_encryption.rs, tests/cases/test_event_listener.rs, tests/cases/test_iterator.rs, tests/cases/test_metadata.rs, tests/cases/test_prefix_extractor.rs, tests/cases/test_rocksdb_options.rs, tests/cases/test_statistics.rs, tests/cases/test_table_properties.rs, tests/cases/test_table_properties_rc.rs, tests/cases/test_titan.rs
- Add some additional options to flush function (https://github.com/tikv/rocksdb/pull/337)
- Support getting statistics of active memtable
- Support getting flush size of write buffer manager
=> port memtable stats accessors

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
=> update compaction thread limiter interface

.gitmodules
=> update rocksdb for checkpoint fix

.gitmodules
To include https://github.com/tikv/titan/pull/282
=> Update titan to avoid titan manifest mutex

.gitmodules, librocksdb_sys/build.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
=> update rocksdb and adapt for check in range

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
The check at rocksdb is https://github.com/tikv/rocksdb/pull/348
=> support config io rate limiter auto-tune smooth window

librocksdb_sys/Cargo.toml, src/sst_partitioner.rs
Include:
- https://github.com/tikv/titan/pull/274
- https://github.com/tikv/titan/pull/281
- https://github.com/tikv/titan/pull/283
=> Update titan to use async init gc and avoid manifest io mutex

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, scripts/format-diff.sh, src/rocksdb_options.rs, tests/cases/test_ingest_external_file.rs
We'd like verify checksum before ingestion to avoid corrupted SST being ingested.
BTW, update titan to include https://github.com/tikv/titan/pull/289
=> Support setting verify checksum for ingest option

.gitmodules
Include https://github.com/tikv/rocksdb/pull/358
=> Fix partial synced inactive WAL

Makefile
Also update the tool chain script.
=> Ensure writes to WAL tail during FlushWAL(true) will be synced (facebook#10560) (#357)

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
Port `disable_manual_compaction` and `enable_manual_compaction` to tikv-6.5
Ref #735.
=> *: support enable & disable manual compaction work.

librocksdb_sys/crocksdb/c.cc
=> Fix bloom filter 7.1

librocksdb_sys/Cargo.toml
This is a recurring of https://github.com/tikv/rust-rocksdb/issues/750
=> Fix build by upgrading bindgen

librocksdb_sys/Cargo.toml
=> Upgrade bindgen

.gitmodules
Ref https://github.com/tikv/tikv/issues/17995, ref https://github.com/tikv/rocksdb/pull/401.
Update rocksdb to fix clock-skew issues.
=> Update rocksdb: fix clock skew if enabling auto-tuned. 

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
Provide RocksDB's HyperClockCache as a shared cache option.
=> Add hyper clock cache

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs
More details at https://github.com/tikv/tikv/pull/18096.
=> Support writes during ingestion

src/merge_operator.rs, src/metadata.rs, src/rocksdb.rs
=> Fix undefined behavior caused by dereferencing

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs
This is a manual cherry-pick of https://github.com/tikv/rust-rocksdb/pull/814
More details at https://github.com/tikv/tikv/pull/18096.
=> [cp-to-7.5] Support writes during ingestion (#814)

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs
This reverts commit ffdc5b1ad601fbabdce5c130a970c1a0e2addbaf.
It was unintentionally merged while being tested.
=> Revert "Add blob_raw_size to Titan blob index FFI (#834)"
