librocksdb_sys/build.sh
Download zlib from github to avoid the url at zlib.net not available.
@BusyJay @siddontang PTAL
=> download zlib from github

src/external_file.rs
Hi,
This PR adds `Send` trait for `SstFileWriter`, which is needed for https://github.com/pingcap/tikv/pull/1561
PTAL @BusyJay @zhangjinpeng1987 @siddontang @ngaut
=> add Send trait for SstFileWriter

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
Call `pause_bg_work` will wait until all currently running background processes finish, this will guarantee that there is no rocksdb's background threads. 
@BusyJay @siddontang PTAL
=> pause background work

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
When you set the path to rocksdb directory in memory like in /dev/shm,
you need to set the wal_dir and WAL_ttl_seconds options if you want to
recover your in-memory RocksDB database after a machine reboot.
See: https://github.com/facebook/rocksdb/wiki/How-to-persist-in-memory-RocksDB-database
=> Add RocksDB options for in memory configurations.

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/main.rs, src/rocksdb_options.rs
Some options are removed from RocksDB 5.2+, removing these is ok and has no problem with 5.1, only we need to remove `set_disable_data_sync` in TiKV later. 
=> remove useless rocksdb API

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
We can use create_info_log to let RocksDB generate info LOG to other places with special name.
@BusyJay @overvenus @zhangjinpeng1987
=> create info log

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
1) Get block cache usage size. 
2) `crocksdb_get_options ` not return `rocksdb::Options` for `default` cf but return `rocksdb::DBOptions`, so we implement `get_options` by `get_options_cf`.
@siddontang @BusyJay PTAL
=> Get block cache usage size

src/rocksdb.rs
So that we can use `#[derive(Debug)]` for structs that contains `DB`.
@siddontang @zhangjinpeng1987 PTAL
=> *: implement debug for DB

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/test_ingest_external_file.rs
Hi,
This PR adds a constructor for `SstFileWriter`, which could be used without specified cf handle.
It's needed by https://github.com/pingcap/tikv/pull/1798
PTAL @zhangjinpeng1987 @siddontang @BusyJay
=> add constructor for sstfilewriter

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h
If we don't implement `GetFilterBitsBuilder` interface for `FilterPolicy`, the default one which return null will effect the filter type, we except `FullFilter` but we get `BlockBasedFilter`.
https://github.com/facebook/rocksdb/blob/master/table/block_based_table_builder.cc#L74
=> add GetFilterBitsBuilder/GetFilterBitsReader for c bloom

librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs
Reverts pingcap/rust-rocksdb#68
compile fails under macOS.
the recommended way of compiling (dynamic linked) is:
``LIBRARY_PATH=/usr/local/lib CXXFLAGS=-I/usr/local/include cargo build``
=> Revert "explicit fail when rocksdb version is too low"

src/rocksdb_options.rs
=> rocksdb_options: fix #77 memory leaks in cache

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
In our use cases we don't need to clone filter, and CompactionFilterHandle is quite complex.
=> rocksdb: implement Clone trait for Options

.travis.yml, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/rocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs, src/table_properties.rs, tests/test_table_properties.rs
- reduce allocation
- collect lazily
- strict access mode
=> user properties: clean up API

librocksdb_sys/build.sh
Makefile will link to jemalloc automatically if it's installed on the system. But this may lead to unexpected build failure if installed jemalloc is outdated. Actually rustc will link to built-in jemalloc automatically, hence we can just skip it when building native library.
=> build: disable jemalloc

librocksdb_sys/src/lib.rs, src/main.rs, tests/test_rocksdb_options.rs, tests/test_statistics.rs
So it will be more easy to unify configuration later.
=> *: remove redundant DB prefix

librocksdb_sys/src/lib.rs
These enums are often embedded in other structs, impl `Debug` so that `Debug` can be also derived for other structs. 
E.g. 
```rust
#[derive(Debug)]
struct Config {
style: DBCompactionStyle,
}
```
=> librocksdb_sys: impl Debug for enums that have variants

Cargo.toml, Makefile, src/main.rs, src/merge_operator.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/test.rs, tests/test_column_family.rs, tests/test_compaction_filter.rs, tests/test_delete_files_in_range.rs, tests/test_delete_range.rs, tests/test_event_listener.rs, tests/test_ingest_external_file.rs, tests/test_iterator.rs, tests/test_prefix_extractor.rs, tests/test_rocksdb_options.rs, tests/test_slice_transform.rs, tests/test_table_properties.rs
This change breaks API, but makes code more clean and readable too.
=> Add type 'ColumnFamilyDescriptor' for 'open' related methods

src/rocksdb.rs, tests/test_iterator.rs
It's intuitive to hold a lifetime for iterator because it's safe and sound as long as the underlying database is not dropped. However, we usually wrap database into an `Arc` in threaded code. In this case, lifetime is not necessary anymore as we can always clone the database. And a lifetime will make it hard to store and update an iterator in a struct due to the self-reference problem (this may be improved in the future in rust), which is very important to write lazy asynchronous code.
So this pr makes iterator constructor accept a `Deref` instead of a `&DB`, so we can pass `&DB`, `Arc<DB>` or anything else as we need.
=> iterator: use deref instead of pure db reference

librocksdb_sys/crocksdb/c.cc
Add version check so that we can know exactly what's going wrong instead of a bunch of declaration error.
=> build: check rocksdb version when compiling

src/rocksdb_options.rs, tests/test_rate_limiter.rs
Signed-off-by: UncP <uncp.xu@gmail.com>
The rust-rocksdb::RateLimiter does not have to be mutable, because rocksdb::RateLimiter inside is already mutable.
Created this pr to fix TiKV compilation error.
=> Update rate_limiter api

librocksdb_sys/rocksdb/db/compaction_job.cc, librocksdb_sys/rocksdb/db/db_compaction_test.cc, librocksdb_sys/rocksdb/db/db_impl.cc, librocksdb_sys/rocksdb/db/version_set.cc, librocksdb_sys/rocksdb/include/rocksdb/convenience.h
Cherry-pick bug-fix about using DeleteRange mix with DeleteFilesInRange.
[delete range bug-fix](https://github.com/facebook/rocksdb/commit/966b32b57c673774ea677fe3a40d255e6c8916ba)
[prevent overlapping](https://github.com/facebook/rocksdb/commit/78d1a5ec7263e380700b5fa36b2ffcd1cb265a2f)
=> Prevent overlapping

.travis.yml, librocksdb_sys/build.rs
Also enabled macOS build on Travis CI to test it.
=> Fix macOS build

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/test_rocksdb_options.rs
`crocksdb_options_set_max_bytes_for_level_multiplier` need `double` parameter but we pass `c_int`, it will cause numeric error.
=> Fix type error

librocksdb_sys/crocksdb/c.cc
`Apple LLVM (clang)` does not support VLA of non-POD types, leading to the following compilation error for `librocksdb_sys` on MAC OS X:
```
cargo:warning=crocksdb/c.cc:3420:15: error: variable length array of non-POD element type 'rocksdb::Slice'
cargo:warning=  Slice starts[num_ranges];
cargo:warning=              ^
cargo:warning=crocksdb/c.cc:3421:15: error: variable length array of non-POD element type 'rocksdb::Slice'
cargo:warning=  Slice limits[num_ranges];
cargo:warning=              ^
cargo:warning=crocksdb/c.cc:3422:18: error: variable length array of non-POD element type 'rocksdb::RangePtr'
cargo:warning=  RangePtr ranges[num_ranges];
```
Other wrapped calls also use std::vector, hence i'm assuming heap allocation is not prohibited by design.
=> [fix] Convert variable-length arrays to std::vector

librocksdb_sys/build.rs
Add necessary build flag to support compiling on FreeBSD successfully. A
similar change could be made to support OpenBSD and DragonflyBSD.
=> Support building on freebsd

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/perf_context.rs
Exploit the `PerfContext` for better debugging. See the test for example usage.
Most of the code in this PR is boring and is generated by a script :)
=> *: add PerfContext

src/metadata.rs, src/rocksdb.rs, tests/test_compact_range.rs, tests/test_compaction_filter.rs, tests/test_delete_range.rs, tests/test_iterator.rs, tests/test_prefix_extractor.rs, tests/test_rocksdb_options.rs
`LevelMetaData` and `SstFileMetaData` are only valid when `ColumnFamilyMetaData` is valid, so we need to add lifetime for them.
=> metadata: fix lifetime

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/merge_operator.rs, src/rocksdb.rs, tests/test.rs, tests/test_ttl.rs
Support DBWithTTL::Open interface, and add open_cf_with_ttl in rocksdb.rs
=> Supoort db with ttl open

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/event_listener.rs, src/lib.rs, tests/test_event_listener.rs
Add `on_stall_conditions_changed` to `EventListener`, so that it could be shown in Grafana.
`triggered_writes_stop` and `triggered_writes_slowdown` are also exposed as interfaces.
=> Add on_stall_conditions_changed to EventListener

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs
Integrate [`Ldb Tool`](https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool) [`ldb_tool.cc`](https://github.com/facebook/rocksdb/blob/master/tools/ldb_tool.cc) of RocksDB.
`run_ldb_tool` encapsulates `LDBTool::Run`, which can accept the argument from cmd line.
=> Add function run_ldb_tool

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/test_ingest_external_file.rs
Provide an optimized version of `ingest_external_file_cf`. It will first try to ingest files without blocking and fallback to a blocking ingestion if the optimization fails. See the comment for more details.
=> Provide an optimized file ingestion method

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_encryption.rs
With this diff, we can pass a self-defined base env for encrypted env.
=> Support self-defined base env for encrypted env 

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
1. Update RocksDB with a bugfix and the ldb options support
2. Pass the options to run ldb tool so that we can use the environment created outside
=> tools: pass options to ldb

librocksdb_sys/Cargo.toml
(cherry picked from commit 5c9bcda88d9a1f55b812093394528def871739fe)
=> [cherry-pick] Use libz-sys from crates.io (#230)

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/cases/test_ingest_external_file.rs
Cherry pick from master, the option to disallow write stall on flush is not supported in RocksDB 5.8, so I remove that optimization in this PR.
=> Provide an optimized file ingestion method (#218)

librocksdb_sys/crocksdb/c.cc
There is no guarantee that the inner pointer of shared_ptr will be nullptr when shared_ptr is invalid. We should use more idiomatic method to judge if a shared_ptr is valid.
=> Fix misuse of shared_ptr 

.gitmodules
Update .gitmodules to point to pingcap/rocksdb tikv-3.0 branch. Also update rocksdb to include the following changes:
75133b1b6 2019-03-26 yiwu@pingcap.com     Fix SstFileReader not able to open ingested file (#5097)
7ca9eb754 2019-03-26 yiwu@pingcap.com     Fix BlockBasedTableIterator construction missing index_key_is_full parameter
=> Update .gitmodules to point to pingcap/rocksdb tikv-3.0 branch

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_delete_range.rs
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
After this change, we can reuse WriteBatch between multiple writings.
=> pass WriteBatch ref to db.write

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/titan.rs
I need a way to know the sequence number from DB and snapshot to check which snapshot is newer soon.
PTAL @yiwu-arbug @zhangjinpeng1987
=> *: support getting sequence number

src/rocksdb_options.rs, tests/cases/test_iterator.rs, tests/cases/test_rocksdb_options.rs
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
We will refactor TiKV IterOptions and reduce memory copy, this PR is a preparation.
=> Use Vec parameter for ReadOptions' bound APIs.

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, src/titan.rs, tests/cases/test_rocksdb_options.rs
Adding `BlockBasedTableOptions::set_block_cache` so we can set shared block cache instance to different column family and different DB instance.
Also adding `LRUCacheOptions` and `Cache` structs.
=> Add BlockBasedTableOptions::set_block_cache

src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
This is to get around borrow checker for TiKV side of changes. Other APIs also pass in structs as reference.
=> Pass cache as reference to BlockBasedOptions::set_block_cache

Cargo.toml, benches/cases/bench_wal.rs, benches/cases/mod.rs, benches/mod.rs, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
See https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L615
Add the recycle log configuration, in my local benchmark, the result is:
```
test cases::bench_wal::bench_wal_disalbe_wal         ... bench:       8,147 ns/iter (+/- 99,123)
test cases::bench_wal::bench_wal_no_sync             ... bench:      30,064 ns/iter (+/- 22,045)
test cases::bench_wal::bench_wal_with_recycle_log    ... bench:      88,007 ns/iter (+/- 60,683)
test cases::bench_wal::bench_wal_without_recycle_log ... bench:     106,474 ns/iter (+/- 126,216)
```
In our IDC with Optane disk:
```
test cases::bench_wal::bench_wal_disalbe_wal         ... bench:       9,637 ns/iter (+/- 107,219)
test cases::bench_wal::bench_wal_no_sync             ... bench:      18,944 ns/iter (+/- 125,435)
test …
```
=> add recycle log configuration

src/rocksdb.rs
it is possible using a non-default comparator, e.g., reverse comparator.
=> Shouldn't assume lexicographical ordering for key Range

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h
Rust API passes `f64` as `float` instead of `double` which sets these configs with an unexpected value.
```rust
pub fn set_discardable_ratio(&mut self, ratio: f64) {
unsafe {
crocksdb_ffi::ctitandb_options_set_discardable_ratio(self.inner, ratio);
}
}
```
=> Fix titan config

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs
Summary:
`db.create_cf` call `crocksdb_create_column_family`, which doesn't pass titan specific options to titan. Fix it by calling `ctitandb_create_column_family` when titan is enabled.
Test Plan:
Manual test when enabled titan, tikv pass correct titan options when creating new CFs.
Will add unit test in later patch.
=> Fix create_cf not passinig titan specific options to titan

librocksdb_sys/Cargo.toml, librocksdb_sys/libtitan_sys/Cargo.toml, librocksdb_sys/libtitan_sys/build.rs
Fix build script not passing portable flag to titan.
Tested by build with `cargo build -vv --features portable` and check actual compile command does not contain -march=native flag. e.g.
```
[libtitan_sys 0.0.1] /usr/bin/c++  -DBZIP2 -DHAVE_PCLMUL -DHAVE_SSE42 -DLZ4 -DOS_LINUX -DROCKSDB_FALLOCATE_PRESENT -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PLATFORM_POSIX -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -DROCKSDB_SUPPORT_THREAD_LOCAL -DSNAPPY -DZLIB -DZSTD -I/data/rust-rocksdb    /target/debug/build/snappy-sys-ff485584675450be/out/build -I/data/rust-rocksdb/target/debug/build/bzip2-sys-593753ebc763ecf6/out/include -I/data/rust-rocksdb/target/debug/build/lz4-sys-c5ffb8280e1f82b8/out/include …
```
=> Fix Titan portable build

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
This PR exports more options in RocksDB `BlockBasedTableOptions`, because we want to use [Partitioned Index Filters](https://github.com/facebook/rocksdb/wiki/Partitioned-Index-Filters#how-to-use-it).
There is an issue [cache_index_and_filter_blocks causes Get slowdown](https://github.com/facebook/rocksdb/issues/3961) in rocksdb, and we test the recommend `Partitioned Index Filters` in java JNI binding, it works well.
So i think these options should be exported to rust-rocksdb users too.
The rocksdb log in test case `test_partitioned_index_filters` as below:
```
cache_index_and_filter_blocks: 1
cache_index_and_filter_blocks_with_high_priority: 1
pin_l0_filter_and_index_blocks_in_cache: 1
pin_top_level_index_and_filter: 1
index_type: 2
hash_index_allow_collision: 1
checksum: 1 …
```
=> (feat) Supports partitioned index filters settings for BlockBasedOptions

Cargo.toml, librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs
Adding feature "jemalloc". When enabled, rocksdb "WITH_JEMALLOC" will be enabled. This does NOT affect whether jemalloc is use or not. Mostly it only affect how rocksdb calculate block cache size: if "WITH_JEMALLOC" is on, it will use `malloc_usable_size()` (size allocated by jemalloc) to calculate size of each entry of block cache, instead of the requested size of the allocation.
Tested by running `cargo build --features jemalloc -vv` and check rocksdb compile flags from the output.
=> Add feature "jemalloc" to enable "WITH_JEMALLOC" on rocksdb

src/perf_context.rs
Fixing perf context test failure with `cargo test -- --test_threads=1`. The test assume default perf level is `PerfLevel::EnableCount`, which apparently will affected by other tests.
Tested by running `cargo test -- --test_threads=1`.
Closing #318 
=> Fix perf context test

librocksdb_sys/build.rs
RocksDB cmake default to build with gflags but we actually don't depend on it. We thought ldb would depend on gflags but it actually not. Disabling it.
Tested by build tikv with the change. Tried `tikv-ctl --db=xxx scan --from=xxx --to=xxx` and it works.
=> Not to compile with gflags

librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs
When jemalloc feature is on, add jemalloc-sys dependency and pass its lib path to rocksdb.
Tested on ubuntu with libjemalloc-dev uninstalled.
=> Add jemalloc-sys dependency when jemalloc is enabled

librocksdb_sys/build.rs, librocksdb_sys/libtitan_sys/build.rs, tests/cases/mod.rs, tests/cases/test_compression.rs
`register_dep("Z")` correctly set the include path for zlib, but fail to set the path to libz.a. RocksDB cmake script expect libz.a be place under ${DEP_Z_ROOT}/lib, but libz-sys place it under ${DEP_Z_ROOT}/build. Fixed it.
Also added a test to make sure possible compression types are all linked.
=> Avoid build require system zlib

Cargo.toml, librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs, librocksdb_sys/libtitan_sys/build.rs, src/perf_context.rs, tests/cases/mod.rs, tests/cases/test_compression.rs
Cherry-picking the following changes that fixes zlib, jemalloc and gflags dependencies, and fixes a flaky test:
```
6ead62c 2019-07-25 yiwu@pingcap.com     Avoid build require system zlib (#303)
9246b9c 2019-07-25 hi@breeswish.org     Skip jemalloc options on specific platform (#324)
7a8dd73 2019-07-22 yiwu@pingcap.com     Add jemalloc-sys dependency when jemalloc is enabled (#320)
6f2c632 2019-07-23 yiwu@pingcap.com     Not compile with gflags (#322)
09b8032 2019-07-22 yiwu@pingcap.com     Fix perf context test (#321)
d67f38e 2019-07-21 yiwu@pingcap.com     Add jemalloc feature (#319)
```
Also update rocksdb to fix compile error with gcc9:
```
7a03c83ed 2019-07-23 psergey@askmonty.org Fix MyRocks compile warnings-treated-as-errors on Fedora 30, gcc 9.1.1 (#5553)
```
=> Cherry-pick build and dependency fixes

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
Adding LRUCacheOptions::set_no_dump_allocator, so we can use JemallocNoDumpAllocator of rocksdb to exclude some LRU Cache, like block cache, from core dump.
=> Adding jemalloc-nodump-allocator option for lru-cache

.gitmodules
Created a tikv-3.0 branch for Titan and update rust-rocksdb tikv-3.0 branch to point to it. Also cherry-picking the following Titan changes:
```
19ea115 2019-08-19 yiwu@pingcap.com     cmake auto clone rocksdb (#60)
f0964aa 2019-08-20 keao.yang@yahoo.com  Add benchmark script (#57)
d7b4091 2019-08-04 wujy.cs@gmail.com    Limit blob file read IO with rate_limiter (#54)
```
=> Update titan branch to tikv-3.0 specific branch

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_column_family.rs
Update `ColumnFamilyOptions` to support `DoublySkipList` in memtable.
=> support doubly skiplist

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
The option is useful for catching LSM tree corruption. Adding it.
=> Add force_consistency_checks option

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/event_listener.rs, src/lib.rs, tests/cases/test_event_listener.rs
Add OnBackgroundError handler API.
For the API, also adding crocksdb_status_ptr_t struct, which may be later extend to allow setting a different status (since rocksdb OnBackgroundError allow overriding the background error).
=> Add OnBackgroundError handler API (#349)

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
The option is useful for catching LSM tree corruption. Adding it.
=> Add force_consistency_checks option (#342)

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_titan.rs
Note that, TitanDBOptions is the superclass of RocksDBOptions. But we pass RocksDBOptions with Titan related Options separately, so we should copy the RocksDB part into TitanDBOptions.
=> Fix titan cf options

src/titan.rs
Found via valgrind.
Signed-off-by: Brian Anderson <andersrb@gmail.com>
=> Fix a memory leak in TitanDBOptions::set_dirname

.gitmodules
Since both tikv-3.0 and tikv-3.1 are using the same rocksdb, titan and rust-rocksdb branch, changing the branch name to tikv-3.x.
Also update rocksdb with the following change for 3.x branch:
```
b047a2a6d 2019-11-26 yiwu@pingcap.com     Fix DBFlushTest::FireOnFlushCompletedAfterCommittedResult hang (#6018)
7f1d9f2c8 2019-11-26 harrywong@live.com   Removed const fields in copyable classes (#5095)
59f71ee61 2019-11-26 siying.d@fb.com      Rename InternalDBStatsType enum names (#5779)
1ee718b3b 2019-11-26 xy.tao@outlook.com   Fix blob context when db_iter uses seek (#6051)
129ad9c95 2019-11-26 bupt2013211450@gma.. fix unstable unittest caused by #5958 (#6061)
88cd73817 2019-11-26 bupt2013211450@gma.. Fix corruption with intra-L0 on ingested files (#5958)
4d6616422 2019-11-26 thomasf@fb.com …
```
=> Update rocksdb. Update rocksdb and titan branch for tikv 3.x

librocksdb_sys/Cargo.toml
Using bindgen 0.52 will conflict with bindgen 0.51 using by grpcio crate. See https://github.com/tikv/rust-rocksdb/pull/402/files#r359639449
Change to use 0.51 instead.
=> update bindgen version

src/lib.rs, src/perf_context.rs, src/rocksdb.rs, tests/cases/test_delete_files_in_range.rs, tests/cases/test_delete_range.rs, tests/cases/test_ingest_external_file.rs, tests/cases/test_iterator.rs, tests/cases/test_prefix_extractor.rs, tests/cases/test_rocksdb_options.rs, tests/cases/test_slice_transform.rs, tests/cases/test_table_properties.rs, tests/cases/test_titan.rs
This PR changes some method signatures of `DBIterator`: return `Result` instead of `bool` for `valid`, and all its callers.
=> iterator: fix the behavior about valid

.travis.yml
Update travis to bulid with xcode11.3, to catch compile error unique to clang11. Tested with a version of rocksdb with clang11 compile errors and see the error in travis CI: https://travis-ci.org/tikv/rust-rocksdb/jobs/634612576?utm_medium=notification&utm_source=github_status
=> Travis mac build with xcode11.3

src/rocksdb.rs
Cherry-picks #424 to `tikv-3.x`. Needed by tikv/tikv#6536.
=> [3.x] Mark SequentialFile as Send (#424)

src/lib.rs, src/rocksdb.rs, src/table_properties_rc.rs, src/table_properties_rc_handles.rs, tests/cases/mod.rs, tests/cases/test_table_properties_rc.rs
In order to create abstract storage engines per https://github.com/tikv/tikv/issues/6402, the abstractions must not contain any generic lifetimes (due to limitations in Rust). In order to create abstractions for the RocksDB TablePropertiesCollection APIs, I have created a new set of bindings that use reference counting instead of lifetimes.
These live in `table_properties_rc` module, do not replace the existing API, and are not reexported at the crate level like other types. At present they are only suitable for use by TiKV, and only implement the features used by TiKV.
I have included a test case the purpose of which is simply to prove that the reference counting does not have any basic use after free errors, and I have run it under valgrind.
After this is merged I will upgrade TiKV and …
=> Add reference-counted TablePropertiesCollection bindings

librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
I add interface `set_target_path_id` for `CompactOptions`. 
`target_path_id` could make user able to choose db path in which the output data of this compaction job store.
=> add interface set_target_path_id for CompatOptions

src/lib.rs, src/perf_context.rs
As commentted in https://github.com/tikv/rust-rocksdb/pull/442#issuecomment-595001970, `PerfContext` is naturally `!Send` because it contains a raw pointer.
Reverting #442 makes this crate compile on stable Rust.
=> Revert "implemented !Send for PerfContext struct (#442)"

librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/src/generated.rs
Update rocksdb and titan with the following changes:
rocksdb
```
906258cb2 2020-03-08 hawking.rei@gmail... Add WAL write duration metric (#153)
17aa69c29 2020-02-18 yiwu@pingcap.com     Disable unnecessary java and cmake builds in travis (#150)
96d7d163a 2020-02-14 xy.tao@outlook.com   [PCP-21] Titan GC doesn<E2><80><99>t affect online write (#147)
77a354652 2020-02-14 johnsonqrr@gmail.com fix config (#148)
0e755d960 2020-02-04 anand76@devvm1373... Force a new manifest file if append to current one fails (#6331)
dcb00a341 2020-02-04 siying.d@fb.com      Bug when multiple files at one level contains the same smallest key (#6285)
aa7a1e9b0 2020-02-04 ltamasi@fb.com       Adjust thread pool sizes when setting max_background_jobs dynamically (#6300)
```
titan:
```
3fcbc2b 2020-03-04 …
```
=> Update rocksdb and titan

.gitmodules
Fix rust-rocksdb/master should point to rocksdb/6.4.tikv. Also update rocksdb with the change:
```
979a985cf 2020-03-25 yiwu@pingcap.com     Add counter in perf_context to time cipher time (#158)
```
=> fix rocksdb branch and update rocksdb

.travis.yml, Cargo.toml, librocksdb_sys/Cargo.toml
#463 forget to expose `static_libcpp` feature to top level Cargo.toml. Fixing it.
=> expose static_libcpp feature

src/logger.rs, tests/cases/test_logger.rs
Signed-off-by: Wangweizhen <hawking.rei@gmail.com>
UCP https://github.com/tikv/tikv/issues/6496
Fix this error from clippy.
```
this public function dereferences a raw pointer but is not marked `unsafe`
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref
```
=> Change Logger trait to accept string slice instead of raw pointer

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/logger.rs, tests/cases/test_logger.rs
remove Valist and make logger return the log string instead of ```snprinf``` by client.
Signed-off-by: Wangweizhen <hawking.rei@gmail.com>
=> logger: remove valist

librocksdb_sys/crocksdb/c.cc
* RocksDB may print large log lines up to 64k. The default 1k buffer for `logv` is too small and truncates rocksdb log. When we detect log line is too long, we allocate a large enough buffer on heap and try again.
* When log level is not specified, defaults to header level.
=> logger: use larger buffer and fix header level log

librocksdb_sys/Cargo.toml
Jemallocator has not been active for several months. We published our
own fork, which upgraded jemalloc to 5.2.1.
=> librocksdb_sys: use tikv-jemalloc-sys

librocksdb_sys/Cargo.toml
Jemallocator has not been active for several months. We published our
own fork, which upgraded jemalloc to 5.2.1.
=> librocksdb_sys: use tikv-jemalloc-sys (#520)

librocksdb_sys/Cargo.toml, librocksdb_sys/libtitan_sys/Cargo.toml
bozaro/lz4-rs#23 is merged and released, we can switch to crates.io now.
This is one step forward for #340.
=> *-sys: use release lz4

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/lib.rs, src/rocksdb.rs, src/write_batch.rs, tests/cases/test_column_family.rs, tests/cases/test_ttl.rs
Add iter method for WriteBatch so that users can read every key-value pairs stored in WriteBatch.
Do not merge this PR before https://github.com/tikv/rocksdb/pull/177
=> Add iter method for WriteBatch

librocksdb_sys/Cargo.toml, librocksdb_sys/libtitan_sys/Cargo.toml
Signed-off-by: gentcys <iamchencong@gmail.com>
An error occurred while compiling on macOS, which described in https://github.com/tikv/tikv/issues/8659.
And it's fixed by https://github.com/rust-lang/libz-sys/commit/81026e996eb3804acf1e6898a3c1d791cdfb59f1.
This PR just update the version of dependency `libz-sys`.
=> libtitan_sys: upgrade libz-sys's version to 1.1.2

librocksdb_sys/bindings/aarch64-unknown-linux-gnu-bindings.rs, librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
Add option setter/getter for max-background-flushes and max-background-compactions, they are backward compatible as per https://github.com/facebook/rocksdb/blob/a242a5830116c2fdd476af79873297a7e0d02410/include/rocksdb/options.h#L567.
Depend on tikv/rocksdb#199
=> Add option for max-background-flushes and max-background-compactions

librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs
Expose dictionary compression options for rocksdb to Tikv. So we could introduce dictionary compression to Tikv to relieve the compression issue. It's part of work [Issue 8635](https://github.com/tikv/tikv/issues/8635).
Issue Number: https://github.com/tikv/tikv/issues/8635
=> Expose rocksdb dictionary compression options setter

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/compaction_filter.rs, src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs, tests/cases/test_iterator.rs
This PR supports to access seqno for every key/value pairs in compaction filter or iterator.
It's helpful to enhance GC in compaction filter in TiKV.
=> expose seqno from compaction filter and iterator 

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/encryption.rs
1. update rocksdb to atomize `RenameFile` in `KeyManagedEncryptedEnv`
2. removed redundant rename logic from key manager
=> rocksdb: Atomize RenameFile in KeyManagedEncryptedEnv

.gitmodules, librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/encryption.rs, src/file_system.rs, src/lib.rs, src/rocksdb.rs
Followup on tikv/rocksdb#216, port related interface to rust, add `file_system_inspected_env` factory method.
=> Port file system inspector

scripts/generate-bindings.sh
`uname -p` returns `AMD Ryzen 7 3700X 8-Core Processor` in my PC. `uname -m` seems to be a better idea on getting the architecture.
Or simply `arch` command works well, but I don't know whether it exists on non-linux system.
=> use `uname -m` instead of `uname -p` to get the architecture

src/encryption.rs, src/file_system.rs, src/lib.rs, src/rocksdb.rs
Accept boxed construct instead of `Arc` to avoid nested arc required to bridge different crates. Also fix a missing export.
=> refactor usage of `Arc`

src/sst_partitioner.rs
Allow sst partitioner methods to be mutable. On RocksDB side these methods are not const methods, thus should be mutable.
=> change sst_partitioner calls to be mutable

librocksdb_sys/Cargo.toml
Due to https://github.com/alexcrichton/bzip2-rs/pull/58 `bzip2-sys` versions above 0.1.8 do not guarantee that bzip2 is statically linked.
Which in turn causes the build to fail depending if pkg-config says bzip2 is available.
=> Update bzip2-sys in order to use "static" feature

librocksdb_sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_ingest_external_file.rs
See the issue [here](https://github.com/tikv/tikv/issues/10430) 
This PR provides the Rust API of setting `IngestExternalFileOptions::write_global_seqno`
Signed-off-by: Yang Zhang <yang.zhang@pingcap.com>
=> Allow setting write_global_seqno option

.gitmodules, librocksdb_sys/Cargo.toml, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/compaction_filter.rs, src/lib.rs, src/rocksdb_options.rs
Allow compaction filter on flush.
Ref: [tikv/rocksdb#pr243](https://github.com/tikv/rocksdb/pull/243)
TODO:
=> Allow compaction filter on flush

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/event_listener.rs, src/lib.rs, tests/cases/test_event_listener.rs
This api allows users to reset status error returned from rocksdb internal error.
Signed-off-by: Xintao <hunterlxt@live.com>
=> Add `reset` for status to allow users to clear internal error

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, src/rocksdb_options.rs
pick rocksdb: https://github.com/tikv/rocksdb/pull/267
=> rocksdb: Commit pipeline when write a WriteBatch for linearizability

src/rocksdb.rs
Signed-off-by: tonyxuqqi <tonyxuqi@outlook.com>
This is needed for TabletFactory to implement Clone().
=> make Cache support Sync and Send

librocksdb_sys/Cargo.toml, librocksdb_sys/libtitan_sys/Cargo.toml
Signed-off-by: Ruihang Xia <waynestxia@gmail.com>
bump `zstd-sys` to `2.0.1+zstd.1.5.2` https://docs.rs/zstd-sys/2.0.1+zstd.1.5.2/zstd_sys/index.html
zstd's release note: https://github.com/facebook/zstd/releases
run `cargo test` with one failing case
```
---- cases::test_rocksdb_options::test_direct_read_write stdout ----
thread 'cases::test_rocksdb_options::test_direct_read_write' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument: Direct I/O is not supported by the specified DB."', tests/cases/test_rocksdb_options.rs:569:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This case also failed on master in my env(
=> update zstd-sys dep

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb.rs, tests/cases/test_column_family.rs
This is useful to detect whether a DB is still hold by other threads.
We may also use reference check to detect whether a DB is obsolete,
but checking the file lock directly provides more safety.
=> *: support check if a db is lock

librocksdb_sys/Cargo.toml
Close #750 
After some searching, I found two similar issues https://github.com/rust-lang/rust-bindgen/issues/2488 and https://github.com/rust-lang/rust-bindgen/issues/2312.
This issue has been fixed in rust-bindgen 0.62.
=> Update rust-bindgen to fix build with clang 16

src/rocksdb.rs, src/rocksdb_options.rs
As title, this is a candidate solution to implement coprocessor cache for raftstore v2.
=> Support get sequence number from UnsafeSnap

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/sst_partitioner.rs
cc https://github.com/tikv/rocksdb/pull/341
=> added next level of output level SST's metadata for compactions 

librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs
Previously, enabling encryption in librocksdb_sys resulted in static linking of OpenSSL, potentially preventing users from utilizing their host system's OpenSSL with important security updates.
This commit removes the requirement for static linking, giving users the flexibility to choose whether to use it or not.
=> librocksdb_sys: no longer static links OpenSSL for encryption

src/compaction_filter.rs, tests/cases/test_compaction_filter.rs
https://github.com/tikv/rust-rocksdb/pull/757 changes the interface of compaction filter, but Titan doesn't. When titan is enabled, it wraps the tikv compaction filter. But Titan only overrides the `FilterV3` but `UnsafeFilter`. So every calling to `UnsafeFilter` would just call the default implement of the base compaction filter which turns out skipping the logic of tikv compaction filter.
This PR includes the interface changes on Titan side https://github.com/tikv/tikv/pull/16054
=> Fix skipping compaction filter logic when titan is enabled

librocksdb_sys/Cargo.toml, librocksdb_sys/build.rs
Cherry-pick #774
---
Previously, enabling encryption in librocksdb_sys resulted in static linking of OpenSSL, potentially preventing users from utilizing their host system's OpenSSL with important security updates.
This commit removes the requirement for static linking, giving users the flexibility to choose whether to use it or not.
=> librocksdb_sys: no longer static links OpenSSL for encryption (#774)

librocksdb_sys/crocksdb/c.cc
Apply RocksDB fix https://github.com/tikv/rocksdb/pull/365, which uses prefix match instead of exact match for determining whether a bloom filter is compatible or not.
Also, revert the change that added the filter type as suffix, since it is unnecessary (all internal filters can be used interchangeably), and is causing compatibility issues (https://github.com/tikv/tikv/issues/17272), i.e. SSTs created before 7.1 with filter meta block named using `rocksdb.BuiltinBloomFilter` are no longer recognized by newer versions of TiKV.
We will probably have to maintain the customized change "prefix match" for a while, to make sure impacted versions are migrated smoothly.
=> Revert bloom filter name extension

librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs, src/rocksdb_options.rs, tests/cases/test_rocksdb_options.rs
When we upgrade RocksDB from 6.29 to 8.10, we did not cherry-pick https://github.com/tikv/rocksdb/commit/40551e21c637c88393cceb5fc662c72ff158545e. Because there was a different solution proposed by Facebook https://github.com/facebook/rocksdb/pull/11701. This PR exposes the option, so that TiKV can tune this when potential regressions are observed.
=> Expose bottommost_file_compaction_delay option

src/rocksdb.rs, tests/cases/test_compact_range.rs
Ref: https://github.com/tikv/tikv/issues/18396
After PR #826, the function `disable_manual_compaction` was enhanced to also stop in-progress manual compactions, whereas previously it would only prevent new and pending compactions in the compaction queue from running.
However, the current implementation doesn't properly support multi-database scenarios. To address this, we need to expose an option that controls whether to set the global canceled flag, allowing callers to stop all in-progress manual compactions when needed.
This PR enables `disable_manual_compaction` to optionally set the global canceled flag based on caller requirements.
=> compaction_opt: expose the global cancellation of manual compaction in disable_manual_compaction().

.gitmodules, librocksdb_sys/crocksdb/c.cc, librocksdb_sys/crocksdb/crocksdb/c.h, librocksdb_sys/src/lib.rs
Corresponding to https://github.com/tikv/titan/pull/334, this commit adds a `blob_raw_size` field to `ctitandb_blob_index_t` and its corresponding Rust binding (DBTitanBlobIndex). The field records the uncompressed size of the blob value.
=> Add blob_raw_size to Titan blob index FFI
